<?php 
return [
    //Skill, Crafted Amount, Name, Crafting Time, Single Item Value, Required Items
    ["Crafting", 10, "Bronze Arrow", 6, 6, [[1, "Bronze Bar"], [1, "Spruce Log"]]],
    ["Crafting", 10, "Iron Arrow", 6, 9, [[1, "Iron Bar"], [1, "Pine Log"]]],
    ["Crafting", 10, "Steel Arrow", 6, 15, [[1, "Steel Bar"], [1, "Oak Log"]]],
    ["Crafting", 10, "Platinum Arrow", 6, 25, [[1, "Platinum Bar"], [1, "Maple Log"]]],
    ["Crafting", 10, "Meteorite Arrow", 6, 35, [[1, "Meteorite Bar"], [1, "Teak Log"]]],
    ["Crafting", 10, "Titanium Arrow", 6, 50, [[1, "Titanium Bar"], [1, "Mahogany Log"]]],
    //["Crafting", 1000, "Astronomical Arrow", 6, 80, [[1, "Astronomical Bar"], [1, "Yew Log"]]],

    ["Mining", 1, "Tin Ore", 3, 5, []],
    ["Mining", 1, "Copper Ore", 3, 5, []],
    ["Mining", 1, "Iron Ore", 4.5, 8, []],
    ["Mining", 1, "Silver Ore", 6, 15, []],
    ["Mining", 1, "Coal Ore", 7.5, 11, []],
    ["Mining", 1, "Gold Ore", 21, 52, []],
    ["Mining", 1, "Platinum Ore", 18, 62, []],
    ["Mining", 1, "Meteorite Ore", 26, 105, []],
    ["Mining", 1, "Diamond Ore", 29.5, 125, []],
    ["Mining", 1, "Titanium Ore", 35, 155, []],

    ["Smelting", 1, "Bronze Bar", 3, 12, [[1, "Tin Ore"], [1, "Copper Ore"]]],
    ["Smelting", 1, "Iron Bar", 5, 18, [[1, "Iron Ore"]]],
    ["Smelting", 1, "Silver Bar", 6, 14, [[1, "Silver Ore"]]],
    ["Smelting", 1, "Steel Bar", 6.5, 30, [[2, "Iron Ore"], [1, "Coal Ore"]]],
    ["Smelting", 1, "Gold Bar", 8, 30, [[1, "Gold Ore"]]],
    ["Smelting", 1, "Platinum Bar", 12, 195, [[3, "Platinum Ore"]]],
    ["Smelting", 1, "Meteorite Bar", 20, 345, [[3, "Meteorite Ore"]]],
    ["Smelting", 1, "Diamond Bar", 22, 115, [[3, "Diamond Ore"]]],
    ["Smelting", 1, "Titanium Bar", 30, 650, [[3, "Titanium Ore"]]],

    ["Woodcutting", 1, "Spruce Log", 3, 6, []],
    ["Woodcutting", 1, "Pine Log", 5, 10, []],
    ["Woodcutting", 1, "Oak Log", 6, 13, []],
    ["Woodcutting", 1, "Maple Log", 6.5, 16, []],
    ["Woodcutting", 1, "Teak Log", 8, 20, []],
    ["Woodcutting", 1, "Chestnut Log", 10, 30, []],
    ["Woodcutting", 1, "Mahogany Log", 12.5, 40, []],
    ["Woodcutting", 1, "Yew Log", 15, 55, []],
    ["Woodcutting", 1, "Redwood Log", 17.5, 75, []],
    ["Woodcutting", 1, "Magical Log", 20, 110, []],


    ["Fishing", 1, "Raw Piranha", 5.2, 5, []],
    ["Fishing", 1, "Raw Perch", 7.5, 8, []],
    ["Fishing", 1, "Raw Mackerel", 8, 10, []],
    ["Fishing", 1, "Raw Cod", 12, 14, []],
    ["Fishing", 1, "Raw Trout", 9, 16, []],
    ["Fishing", 1, "Raw Salmon", 13.5, 17, []],
    ["Fishing", 1, "Raw Carp", 9.5, 18, []],
    ["Fishing", 1, "Raw Zander", 15, 23, []],
    ["Fishing", 1, "Raw Pufferfish", 18.8, 30, []],
    ["Fishing", 1, "Raw Anglerfish", 30, 50, []],

    ["Cooking", 1, "Piranha", 3, 6, [[1, "Raw Piranha"]]],
    ["Cooking", 1, "Perch", 3.5, 10, [[1, "Raw Perch"]]],
    ["Cooking", 1, "Mackerel", 4, 12, [[1, "Raw Mackerel"]]],
    ["Cooking", 1, "Cod", 4.5, 15, [[1, "Raw Cod"]]],
    ["Cooking", 1, "Trout", 5, 18, [[1, "Raw Trout"]]],
    ["Cooking", 1, "Salmon", 6, 18, [[1, "Raw Salmon"]]],
    ["Cooking", 1, "Carp", 7.5, 20, [[1, "Raw Carp"]]],
    ["Cooking", 1, "Zander", 10, 25, [[1, "Raw Zander"]]],
    ["Cooking", 1, "Pufferfish", 12.5, 34, [[1, "Raw Pufferfish"]]],
    ["Cooking", 1, "Anglerfish", 17.5, 55, [[1, "Raw Anglerfish"]]],
];